name: Retrain Model

on:
  push:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r MLProject/requirements.txt

      - run: python MLProject/Membangun_model/modelling.py